In [2]:
y = [3,7]
z=[]

for n in y:
    z.append(2*n)

print(z)


[6, 14]


In [3]:
import numpy as np


a = np.array([3,7])

b=2*a
print(b) 

[ 6 14]


In [4]:
a = np.array([1,2,3,4,5])
b = a+2
c = 3*a
d= a/2

print(a, b, c)
print(d) 

[1 2 3 4 5] [3 4 5 6 7] [ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [5]:
# Q2

from statistics import mode 

arr = np.array([1, 2, 3, 4, 5])
reversed =  arr[::-1]
print(reversed)

x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])


modex = np.argmax(np.bincount(x))
modey = np.argmax(np.bincount(y))

print(modex)
print(modey)




[5 4 3 2 1]
1
1


In [17]:
import numpy as np

w = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

element = w[1, 2]
print(element)

element2 = w[2, 1]
print(element2)

60
80


In [18]:
# q4
bal = np.array()             


TypeError: array() missing required argument 'object' (pos 0)

In [ ]:
# Question-5

